README.md
This PR fixes the JavaScript link from README.md.
=> Adds correct JavaScript link from README.md

README.md, python/lib.cpp, setup.py
Moved all modules under `usearch`
=> Add: Pure Python submodules

.github/workflows/release.yml
=> Revert "Semantic versioning"

.github/workflows/release.yml, python/usearch/client.py, python/usearch/server.py
Minor fixes in client.py and server.py.
Minor Refactor in release.yml.
=> Server client fixes 

swift/Test.swift
=> Fix: Wrap the Swift test in XCTestCase

c/usearch.h, csharp/libusearch.cs, csharp/libusearch.csproj, csharp/test.cs
Feel free to pull these updates or discard if unwanted.
- Refactoring (cleaner interface)
- Add Linux support
- Remove unsafe code
- Update `usearch_label_t` (`uint32_t`) to `usearch_key_t` (`uint64_t`)
=> 160 feature c bindings and semantic kernel integration

include/usearch/index.hpp, python/lib.cpp, python/scripts/test.py, python/usearch/index.py
=> Add: Exact search shortcut

csharp/libusearch.cs, csharp/test.cs
- Use `ulong` instead of `int`
- Fix `usearch_get`
- Add test for `usearch_get`
=> C# bindings updates

rust/lib.rs
add test_add_get_vector, test_add_remove_search_vector test cases
=> add test_add_get_vector, test_add_remove_search_vector

python/README.md
=> Docs: Missing Python import

.github/workflows/release.yml, javascript/usearch.js, package.json, tsconfig.json
Referenced 
- Generating types from JSDoc https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
- JSDoc object types https://stackoverflow.com/a/31573441
=> Improve: TypeScript annotations

.github/workflows/prerelease.yml, .github/workflows/release.yml, CONTRIBUTING.md, build.gradle, include/usearch/index_dense.hpp, include/usearch/index_plugins.hpp, java/README.md, java/cloud/unum/usearch/cloud_unum_usearch_Index.cpp, java/cloud/unum/usearch/cloud_unum_usearch_Index.h, java/test/IndexTest.java, javascript/usearch.js, package.json, setup.py, tsconfig.json
=> Fix: Java OOM and TypeScript annotations

.github/workflows/prerelease.yml, .github/workflows/release.yml, .gitignore, package-lock.json
Closes https://github.com/unum-cloud/usearch/issues/329
=> Use npi ci

csharp/src/Cloud.Unum.USearch.Tests/USearchIndexTests.cs, setup.py, sqlite/lib.cpp
Add Unit Test for issue : 
#345
=> add UnitTest LoadingVector and CreateFileVector

javascript/usearch.ts, package-lock.json, package.json
fix: looks like doxygen having issues with modern import for node modules, see if this helps
=> Fix: for doxygen

.github/workflows/release.yml, docs/conf.py, javascript/usearch.ts, package-lock.json, package.json
I was able to test that it does not fail, but not sure if the docs are really generated:
https://github.com/sroussey/usearch/actions/runs/8565020964/job/23472451179
=> fix ci failure on js docs

javascript/usearch.ts, package.json
=> fix: esm bug in jest

.github/workflows/prerelease.yml, .github/workflows/release.yml, package-lock.json
I ran `npm install` and it automatically updated.
=> Upgrade: update package-lock.json

.github/workflows/prerelease.yml, .github/workflows/release.yml, .gitignore, BENCHMARKS.md, CONTRIBUTING.md, Package.swift, cpp/bench.cpp, golang/lib.go, golang/lib_test.go, include/usearch/index_dense.hpp, include/usearch/index_plugins.hpp, objc/README.md, objc/USearchObjective.mm, objc/include/USearchObjective.h, package-lock.json, python/lib.cpp, python/scripts/test_distances.py, python/usearch/index.py, rust/lib.rs, swift/Index+Sugar.swift, swift/README.md, swift/Test.swift
Thanks to @abetomo, @sdenton4, @brittlewis12, @vardhan, and @MarkReedZ for help 🤗
=> New GoLang, Swift, and Objective-C APIs

javascript/usearch.test.js
=> Text: Fix error message

csharp/README.md, csharp/src/Cloud.Unum.USearch.Tests/USearchIndexTests.cs, csharp/src/Cloud.Unum.USearch/USearchIndex.cs
=> Improve: Add Int8 (sbyte) overloads for C#

cpp/test.cpp, include/usearch/index_dense.hpp, include/usearch/index_plugins.hpp
Added new bfloat16 tests with all cpp tests passing Fixes #553
=> Added bfloat16 interface aswell as type specific tests Fixes #553

python/lib.cpp, python/scripts/test_index.py, python/usearch/index.py
Fixes https://github.com/unum-cloud/usearch/issues/609
Ran all tests:
```
pytest python/scripts/test_index.py
```
=> [python] Enable load/view from any buffer object

.vscode/settings.json, cpp/test.cpp, include/usearch/index.hpp, include/usearch/index_dense.hpp
=> Fix Isolating Removed Entries

javascript/usearch.test.js
- Add test to verify batch search functionality with multiple queries
- Test ensures batch search returns correct results
- Addresses issue https://github.com/unum-cloud/usearch/issues/650
=> Add batch search test for issue #650
