unum-cloud/usearch

include/usearch/usearch.hpp, python/lib.cpp, src/punned.hpp, src/test.cpp
The [`ann-benchmarks`](https://github.com/erikbern/ann-benchmark) has an endpoint to estimate memory-usage of some algorithm implementation. To support that natively, instead of system calls, we add a `memory_usage()` method in C++ and a `memory_usage` computed property to Python. For similar reasons, the `expansion_add` and `expansion_search` are added as mutable computed properties.
=> Add: New stats and config updates for Python

javascript/usearch.js, package.json
A custom wrapper `usearch.js` was created to load and bind the native module, and it is exported using `module.exports`. The `package.json` file was updated to set `"main": "javascript/usearch.js"`, making `usearch.js` as the main entry point for the module.
=> Fix: Use of `require('usearch')` in node

python/usearch/index.py
Implementing the `__del__` method allows to add custom freeing logic to the object when it is finalized.
From [python docs](https://docs.python.org/3/reference/datamodel.html#object.__del__)
> `object.__del__(self)`
> Called when the instance is about to be destroyed. This is also called a finalizer or (improperly) a destructor. 
> `x.__del__()` ... is only called when x’s reference count reaches zero.
=> Improve: Index finalizer method

cpp/bench.cpp, include/usearch/index.hpp, include/usearch/index_dense.hpp, python/lib.cpp, python/usearch/index.py
We have extended the logging and progress-tracking functionality to more methods, allowing users to control the next execution steps by returning a boolean from the progress-tracking function. Check `dummy_progress_t` for more context.
=> Add: Progress tracking and early-stop for serialization

README.md
This symbol is not imported so this broke the example code.
I got this error:
```pycon
>>> matches: Matches = index.search(vector, 10)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'Matches' is not defined. Did you mean: 'matches'?
```
=> Remove error-causing annotation in README

.github/workflows/release.yml
This PR addresses the issue of using an outdated version in the C# release CI job by implementing the changes outlined below.
- The `actions/checkout@v3` action was set to use the default branch that triggered the workflow. I believe this was the root cause of the issue, as this branch (`main-dev`) had an outdated VERSION file.
- Version information was manually extracted from the VERSION file.
- Specified the `main` branch for `actions/checkout@v3` to ensure the use of project files updated by semantic-release.
- The CI job now relies on the updated version in `nuget-package.props`, which is set by `update_version.sh`. Manual extraction from the VERSION file has been eliminated.
=> Build: Fix csharp version update in release.yml

.vscode/settings.json, include/usearch/index_plugins.hpp, python/lib.cpp, python/scripts/bench_exact.py, python/scripts/test_tooling.py, python/usearch/index.py
I've fixed the problem spotted by @ebursztein and added an exact search benchmark for small-scale exact search, standard in LLM apps.
```sh
$ python python/scripts/bench_exact.py --ndim 256 --n 100_000 --q 10 --k 100
Hardware acceleration in USearch:  auto
USearch:  0.013957023620605469
FAISS:    0.04720497131347656
$ python python/scripts/bench_exact.py --ndim 256 --n 100_000 --q 10 --k 100 --half
Hardware acceleration in USearch:  auto
USearch:  0.014386892318725586
FAISS:    0.08691692352294922
```
Even without hardware acceleration from SimSIMD, on the M2 Mac Book Pro:
- USearch performs 3.3x faster than FAISS on single-precision vectors.
- USearch performs 6.1x faster than FAISS on single-precision vectors.
---
The script is located at `python/scripts/bench_exact.py` and has a few …
=> Fix: Exact search accuracy and speed

javascript/usearch.test.js
Test example code
The `BigUint64Array` and `Float32Array` have a length of 10, not 1
```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
BigUint64Array(10) [
42n,
0n,
0n,
0n,
0n,
0n,
0n,
0n,
0n,
0n
]
should loosely deep-equal
BigUint64Array(1) [
42n
]
at TestContext.<anonymous> (/Users/jlarmst/Desktop/typefoundriesdirect/usearch/javascript/usearch.test.js:46:10)
at Test.runInAsyncScope (node:async_hooks:203:9)
at Test.run (node:internal/test_runner/test:573:25)
at Test.processPendingSubtests (node:internal/test_runner/test:318:18)
at Test.postRun (node:internal/test_runner/test:642:19)
at Test.run (node:internal/test_runner/test:601:10)
at async startSubtest (node:internal/test_runner/harness:202:3) {
generatedMessage: true,
code: 'ERR_ASSERTION',
actual: …
```
=> test: usearch-js expected results

CONTRIBUTING.md, java/README.md
This has only been tested on Ubuntu. The Windows version is not tested but likely to be correct.
=> Update Java's step-by-step building and running instructions.

javascript/usearch.js
Just a quick fix for error encountered when using usearch@2.8.14
=> Fix: undefined var error in `remove` api

CMakeLists.txt, include/usearch/index.hpp
Latest versions of libc (>= 2.34, released on August, 2021) have
libpthread built in but in slightly older libcs one has to still
specify -llibpthread to explicitly link it in
The commit makes sure usearch compiles successfully with these
older libcs
It changes nothing on newer libcs as libpthread exists on newer libcs as an empty library
=> Add libpthread for older linux gcc builds

CMakeLists.txt, cpp/test.cpp, include/usearch/index.hpp, include/usearch/index_plugins.hpp
Fix some miscelenious issues encountered while working on #335
1. [Add move construction tests and fix an issue caused by them](https://github.com/unum-cloud/usearch/commit/78ea641c5d4a41341efb0cf2544e557f7619aa28)
ASAN flagged the memset call on empty buffer when the test ran with the added move construction portion
2. [Only consider zero length IO an error if input buffer was larger than zero](https://github.com/unum-cloud/usearch/commit/aafff91bf52e4e151e0b1487724113d38aa4729a)
5. [Move option-override policy opt-in before policy definitions so overr…](https://github.com/unum-cloud/usearch/commit/3731149c9d7d680181addd2bc283c513a9272b11)
=> Fix some miscelenious issues encountered while working on #335

package.json
Enables importing like this:
`import * as usearch from 'usearch'`
https://nodejs.org/api/packages.html#conditional-exports
Without this fix I was seeing this error message:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .../node_modules/usearch/package.json
```
=> Support ES module import

python/usearch/__init__.py
Fix for the importlib error in Python: https://github.com/unum-cloud/usearch/issues/360
Added `import importlib.util` in `python/usearch/__init__.py` to fix the error
=> Fix: Bugfix for importlib attrib error

javascript/usearch.js
Parameter validation update to identify values of type BigIn and Integer
When values are sent in BigInt format, validation automatically fails, preventing the creation of the Index
=> Fix: Add BigInt validation in index creation,Node Support

.github/workflows/release.yml, package.json
This does two things:
1. changes what gets included in npm so that a backup build can proceed. I have tested this in docker linux arm64.
2. adds some info that will hopefully cause prebuildify to correctly cross compile for linux-arm64
Fixes #377
=> Fix build issues on node

build.rs
As mentioned in https://github.com/unum-cloud/usearch/issues/378#issuecomment-2032038967, no error is reported if all build configurations fail.
=> Fix: Ensure Rust build aborts on error

include/usearch/index_dense.hpp
Fixing the warnings below:
```
../../src/inline-thirdparty/usearch/usearch/index_dense.hpp: In lambda function:
../../src/inline-thirdparty/usearch/usearch/index_dense.hpp:711:22: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
711 |         auto allow = [=](member_cref_t const& member) noexcept { return member.key != free_key_; };
|                      ^
../../src/inline-thirdparty/usearch/usearch/index_dense.hpp:711:22: note: add explicit ‘this’ or ‘*this’ capture
../../src/inline-thirdparty/usearch/usearch/index_dense.hpp: In lambda function:
../../src/inline-thirdparty/usearch/usearch/index_dense.hpp:1790:22: error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
1790 |         auto allow = [=](member_cref_t …
```
=> Fix -Wdeprecated-this-capture with GCC 11

javascript/usearch.ts
ncc looks for fixed path (but does accept __dirname, unlike esbuild).
=> trick ncc to include binaries

swift/Test.swift
Add a swift test to demonstrate an issue where replacing the initially-added item in an index makes all subsequently added items no longer visible in `search` results. See issue #399 for more details.
=> Add Swift test to illustrate issue #399

cpp/test.cpp, include/usearch/index.hpp
Found with a test case in lantern.
Quick example:
```
uint32_t n32 = 42;
uint64_t n64 = 42;
uint40_t n40_from_32(n32);
uint40_t n40_from_64(n64);
std::cerr << "n40_from_32: " << std::to_string(n40_from_32) << 
" n40_from_64: " << std::to_string(n40_from_64)  << "\n";
```
This was printing "n40_from_32: 10752 n40_from_64: 42".
After the patch, it prints "n40_from_32: 42 n40_from_64: 42"
=> Fix uint32_t to uint40_t construction and cast

build.gradle, java/cloud/unum/usearch/Index.java, java/cloud/unum/usearch/cloud_unum_usearch_Index.cpp, java/cloud/unum/usearch/cloud_unum_usearch_Index.h, java/test/IndexTest.java
Add `Index.get(int key)` method that returns the contents of the vector on the java heap. This method will throw an
`IllegalArgumentException` if key is not found in the index.
=> Extend java API with vector access

java/cloud/unum/usearch/Index.java, java/test/IndexTest.java
Implement `AutoCloseable.close()` to free underlying resources not controlled by the java runtime.
After `close()` all methods will throw an `IllegalStateException` if called to avoid segfaults in JNI.
=> Java: Free resources via `AutoCloseable.close()`

java/cloud/unum/usearch/Index.java, java/cloud/unum/usearch/cloud_unum_usearch_Index.cpp, java/cloud/unum/usearch/cloud_unum_usearch_Index.h, java/test/IndexTest.java
If the index is `save()`ed to disk we should be able to load it without needing to either correctly guess the
parameters or hope they are ignored/overwritten when the index is loaded.
=> Add java `Index.{load,view}FromPath(String)`

include/usearch/index_plugins.hpp
Previously we were downcasting floats to the target type (e.g. int8_t), and then
clamping to [-100, 100] range. This means that e.g. 129 would be cast to -127 and
then converted to -100, in stead of becoming 100
The fix does clamping first, and then casts the resulting number
(which is guaranteed to be in range [-100, 100], due to clamping)
from source type to target int8_t. Given the clamping, this will never overflow.
=> Clamp before downcasting in float to i8 conversions

MANIFEST.in
Closes https://github.com/unum-cloud/usearch/issues/424
=> Adds `py.typed` to project files

include/usearch/index_plugins.hpp
When converting floating point arrays to binary, we use bitwise OR operations to set the relevant bits in the output
buffer to 1. We do nothing if the bit is zero, so we assume that the bit is zero to start with.
The `memset` statement makes sure this assumption holds.
=> Reset cast buffer so it can be set with bitwise ORs

build.gradle
This PR fixes the following deprecation warnings. 
```
Build file '/home/ch/code/mr/usearch/build.gradle': line 13
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.8/userguide/upgrading_version_8.html#java_convention_deprecation
at build_6knh5cblxyylcg5a00yqlwx4w.run(/home/ch/code/mr/usearch/build.gradle:13)
(Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file '/home/ch/code/mr/usearch/build.gradle': line 14
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: …
```
=> Fix: build.gradle deprecations

javascript/tsconfig-esm.json, javascript/usearch.ts
This PR fixes https://github.com/unum-cloud/usearch/issues/426 by adding `"esModuleInterop": true` to `tsconfig-esm.json` and 
```
const usearch = {
Index,
MetricKind,
ScalarKind,
Matches,
BatchMatches,
exactSearch,
};
export default usearch;
```
to the `usearch.ts` file.
=> Fix: ESM build support

rust/lib.rs
This should fix the problem of segfaulting by checking whether the dimensions are adding up and handling the edge case of hamming distance.
Due to `cxx::Exception` being private I had to create a new error type that wraps C++ Exceptions and can output errors from "rustland".
**Therefore this fix could introduce breaking changes** 
It works in my (small) codebase and passes tests, but due to finding more cases that cause an unexpected segfault in rust, I suggest merging these fixes together later.
=> (breaking) FIX for unexpected segfault when index dimensions don't add up

.github/workflows/prerelease.yml, csharp/src/Cloud.Unum.USearch.Tests/USearchIndexTests.cs
Closes #454
As described in https://github.com/unum-cloud/usearch/issues/454#issuecomment-2267207135, index is initialized as f64 implying `double`s, while the vector that is added and queried is a `float`/f32.
setting the vector to a `double` reliably passes tests locally.
=> Align vector type w index

objc/USearchObjective.mm, objc/include/USearchObjective.h, swift/Index+Sugar.swift, swift/Test.swift
Added a couple of tests in Swift to test both functions.
Tested with `swift build && swift test -v`
Issue: #470
=> Add: Swift & Obj-C bindings for filteredSearch

javascript/README.md
Fix the following error:
```
ReferenceError: assert is not defined
```
Fix the following error:
```
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:
Float32Array(1) [
-0.00017893314361572266
]
should loosely deep-equal
Float32Array(1) [
0
]
```
Reference:. https://github.com/unum-cloud/usearch/blob/242be104de770c12ed1fc938215530b944000b42/javascript/usearch.test.js#L49-L61
=> Docs: Update JavaScript code example

javascript/usearch.test.js
The test code used `const`, so we unified it.
Also, it is better to use `const` than `var`.
=> Test: javascript: Use `const` instead of `var`

javascript/usearch.test.js
It is better to use `assert.throws`.
=> Test: JavaScript Use `assert.throws` to test for exceptions

rust/lib.rs
Solved the issue ```*const cxx::void` cannot be shared between threads safely``` and makes index concurrent for use in Rayon or Actix-web. Example is in https://github.com/jbrummack/create_index
See  #482
=> Make Index sendable and syncable

CONTRIBUTING.md
Remove the phrase since it does not include benchmarks.
Related: https://github.com/unum-cloud/usearch/commit/6da60a6df36827c73b8700f70cffdd6ab1fe8f0f
=> Docs: Update Contribution Guide on JavaScript

javascript/lib.cpp, javascript/usearch.test.js
The return value of index.count() was a boolean, so it was changed to a number.
=> Fix: JavaScript Change the return value of index.count() to a number

javascript/lib.cpp, javascript/usearch.test.js
For example, if you try to add the same key, it aborts.
```
terminate called after throwing an instance of 'std::runtime_error'
what():  Duplicate keys not allowed in high-level wrappers
Aborted (core dumped)
```
Improved error handling to throw JavaScript exceptions.
=> Fix: JavaScript Fix bug in add() that aborts with invalid operations

javascript/lib.cpp, javascript/usearch.test.js
I got an error when I loaded and searched with load() or view().
Code Example:
```js
// Saved with `index.save('index.usearch');` in another script.
index.load('index.usearch');
const results = index.search(new Float32Array([0.2, 0.6, 0.4]), 10);
```
Error:
```
/build/javascript/dist/cjs/usearch.js:314
const result = __classPrivateFieldGet(this, _Index_compiledIndex, "f").search(normalizedVectors, k);
^
TypeError: Search failed
at Index.search (/build/javascript/dist/cjs/usearch.js:314:80)
at Object.<anonymous> (/build/example.js:9:21)
at Module._compile (node:internal/modules/cjs/loader:1469:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
at Module.load (node:internal/modules/cjs/loader:1288:32)
at Module._load (node:internal/modules/cjs/loader:1104:12)
at …
```
=> Fix: JavaScript Fix error when searching after load() and view()

javascript/usearch.test.js
The test itself succeeds, but fails with the following error when deleting the index file created by save() in afterEach().
```
error: "EBUSY: resource busy or locked, unlink 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\usearch.test.index'"
```
Since it is only in Winodws that it fails, we will skip it on Winodws for now.
We will continue to investigate the solution.
=> Test: JS: Skip view() test for now, because it fails on Winodws

include/usearch/index_dense.hpp, javascript/lib.cpp, javascript/usearch.test.js
The index read by view() is read-only.
When I did a remove() on that index, it crashed. (`Segmentation fault (core dumped)`)
Although it is an invalid operation to do a remove() on a view() index, it is not a better way to crash, so we have fixed it to return an error.
=> Fix: Fix crash when trying to remove with read-only index

include/usearch/index.hpp, include/usearch/index_dense.hpp
We would like to have access to these precomputed constants so we can display them to the database operator and compare them against similarly configured indexes with other HNSW implementations.
=> Add getters for precomputed constants for observability

CMakeLists.txt
Tests were priorly not detected by "ctest".
See
https://stackoverflow.com/questions/30250494/ctest-not-detecting-tests.
=> Fixed detection of tests

CMakeLists.txt
For use in a C++ project, we configured CMakeLists.txt to fetch and build USearch.
For example, the following configuration:
```cmake
fetchcontent_declare(
usearch
GIT_REPOSITORY "https://github.com/unum-cloud/usearch.git"
GIT_TAG "v2.16.5"
GIT_SUBMODULES ...)
fetchcontent_makeavailable(usearch)
```
Then it cannot find the header file for the submodule and an error occurs.
For example, the following errors:
```
.../_deps/usearch-src/include/usearch/index_plugins.hpp:37:10: fatal error: fp16/fp16.h: No such file or directory
37 | #include <fp16/fp16.h>
```
So we added a header file to be included in target_include_directories().
=> Make: Include submodule header files

README.md
Hi,
TiDB integrate usearch to supports the HNSW vector search index in its recent versions. I'd like to add an link to the README.
=> Docs: Add TiDB under integrations

python/usearch/index.py
The  Python's`usearch.index.search` method creates an `Index` when performing a similarity search with `exact = False`. `Index` requires all its inputs to be passed by name, but the first parameter, the dimension, was not supplied like that.
This PR fixes this error by assigning a name to the first parameter of the `Index` instance, specifically `ndim`.
=> Fix Python `usearch.index.search` in non-exact similarity search

c/usearch.h
`usearch_count` in the usearch.h misses an argument. 
Also corrected two doc strings.
=> Fix: C: missing argument in usearch_count

golang/lib.go, golang/lib_test.go
Fixed Bug: segfault when run usearch_search() concurrently with golang #564
Add ChangeThreadsAdd() and ChangeThreadsSearch() function to golang api to change the thread limit.
Golang user should stop calling search() function when thread limit reached.
go fmt the code.
=> Bug: segfault when run usearch_search() concurrently with golang

cpp/bench.cpp
Because the parameters in run_punned are of type index_config_t instead of index_dense_config_t, the expansion_add and expansion_search parameters passed from the command line cannot be correctly passed to the function; they always use default values.
=> Fix parameter passing issues in bench.cpp

.vscode/settings.json, python/scripts/test_index.py, python/usearch/index.py
In Python, calling `del index[<key>]` on an `Index` object always raises `TypeError: exceptions must derive from BaseException`.
This PR adds a test case to reproduce the bug.
=> Test: Add test case for failing `del index[<key>]`

java/cloud/unum/usearch/Index.java, java/cloud/unum/usearch/cloud_unum_usearch_Index.cpp, java/cloud/unum/usearch/cloud_unum_usearch_Index.h, java/test/IndexTest.java
Currently, the default native key type of dense index `index_dense_t::vector_key_t` does not match the key type declared for Java bindings. This causes two issues:
* The memcopy in `result::dump_to` overruns the allocated buffer which eventually causes malloc to fail with self-check
* The results returned by search are invalid because when long array is interpreted as int, it causes every second value to be 0 (the current test does not catch this because it checks only one result)
Additionally, this PR fixes a case when the index size is smaller than wanted and eliminates extra copy by dumping results directly to the result array.
=> Fix key type for Java bindings

.vscode/launch.json, .vscode/tasks.json, Package.swift, c/lib.cpp, c/module.modulemap, c/usearch.h, swift/Index+Sugar.swift, swift/Test.swift, swift/USearch.swift, swift/USearchIndex+Sugar.swift, swift/USearchIndex.swift, swift/Util.swift
This PR is a second attempt at #563, but using the C bindings as the basis for Swift interop, rather than the C++ interface. This adds a layer of indirection, but drastically simplifies the interop types. Given that Swift/C++ interop is not yet capable of expressing the necessary types for USearch, this is a better option to split the Objective-C and Swift codebases, and ultimately, to support Swift on Linux.
- A move to Swift errors (rather than NSExceptions). This was proposed separately in #554, and I'm still in favour of that change to improve the Objective-C API, but to have an error mechanism in the Swift API we need some of those changes.
- API consistency, the `clear` method was missing, and it would be better to remain mostly API compatible.
- A re-written Swift layer using the …
=> Swift Linux Support

.github/workflows/release.yml, .vscode/launch.json, .vscode/tasks.json, CMakeLists.txt, Dockerfile, Package.swift, c/lib.cpp, c/module.modulemap, c/usearch.h, cpp/test.cpp, include/usearch/index_dense.hpp, include/usearch/index_plugins.hpp, swift/Test.swift, swift/USearch.swift, swift/USearchIndex+Sugar.swift, swift/USearchIndex.swift, swift/Util.swift
This PR brings a new BF16 interface for adding and retrieving vectors in the C++ SDK and adds a new way to compile Swift bindings on Linux, a much safer Java SDK, and more:
- Thanks to @danpalmer for rewriting the whole Swift binding 🤗 
- Thanks to @anirudlappathi & @egorovcharenko for `bf16` patches 🤗 
- Thanks to @Light-V for noticing type-casting issues in `bench.cpp` 🤗 
- Thanks to @IoeCmcomc for fixing `__delitem__` problem in `index.py` 🤗 
- Thanks to @agoncharuk for fixing key types in the Java Native Interface 🤗
=> BF16 and Swift SDK for Linux

python/usearch/index.py
I want to allow kwargs to `Index.restore()` so that I can pass in arguments like `enable_key_lookups=False`.
=> Allow kwargs in Index.restore

include/usearch/index.hpp
#576
In `context` struct, we can add another member(called `top_for_refine`) of type `top_candidate_t`, which cost very limited memory , actually the capacity is at most 32, because max connectivity is 32 in usearch hnsw algorithm. 
During the execution of `form_reverse_links_`, we use the new added member `top_for_refine` to execute the `refine_` function.
As we add the top_for_refine in the context, it avoid the overhead of repeated construction and deconstruction during the execution of vector index.
=> Fix a correctness bug caused by a wrong memory override

.github/workflows/prerelease.yml, .github/workflows/release.yml
=> Python 3.13t "No-GIL" Builds

.github/workflows/release.yml
This fixes missing targets for C# & JS, that were compiled, but never uploaded.
=> Make: Don't `overwrite` artifacts

include/usearch/index_dense.hpp
In both `load_from_stream` and `view`, we initialize `cast_buffer_` to hold enough slots for a certain number of threads. This number of threads is currently `available_threads_.size()`. However, `available_threads_` gets replaced later in both methods, specifically updating the number of threads to `old_limits.threads()`. This change makes the initialization statement use that value instead.
This was discussed on discord here: https://discord.com/channels/1063947616615923875/1064496121520590878/1382727527738376283
=> Fix initialization of cast_buffer_ in load_from_stream and view.

csharp/src/Cloud.Unum.USearch.Tests/USearchIndexTests.cs, csharp/src/Cloud.Unum.USearch/USearchIndex.cs
Adds an Add method that takes a byte array to be used in for scalar type B1.
Fixes #625
=> feat(csharp): Handle B1 arrays when Add():ing to index

rust/lib.rs
Fixes https://github.com/unum-cloud/usearch/issues/629
Add another vector to Index after changing metric in the test.
Afterwards, It would be wise to write tests for each VectorType since they have different implementations.
Anyway, the fix has been tested on all of them.
=> Fix: Using a custom metric results in a segfault

CONTRIBUTING.md, include/usearch/index.hpp, javascript/lib.cpp, javascript/usearch.test.js, javascript/usearch.ts, python/lib.cpp, python/scripts/test_index.py, python/usearch/index.py
Thanks to @Stefano-t the Python and JS bindings require one less step to start working with a restored index. It was a common usability issue, and now it's gone!
=> Multi-threading Usability in Python & JavaScript

golang/lib.go, golang/lib_test.go
Currently, golang API only support float32 as input type.  This PR add new interfaces such as AddWithPointer, SearchWithPointer with unsafe.Pointer instead of []float32 in order to support all types.
=> Broader GoLang API
